### PR TITLE
Judging Proposal: Community Voting Model

### PR DESCRIPTION
**Pull request by maggie-j-liu**

### CODE REVIEW

**Comment by sampoder** [comment]
Thank you Maggie! for both of your proposals.... if you know how I can mail you a cookie, I'll mail you a cookie (or two... probs. not 50 though)

**Comment by 0jas0jas** [comment]
Community voting sounds exciting for the attendees, which is very cool. Also, I wasn't there at Assemble ☹️ so could someone please summarise how judging happened then?

**Comment by maggie-j-liu** [comment]
Awesome writeups in the Assemble repo :D https://github.com/hackclub/assemble/blob/main/the-event/judging.md

**Comment by 0jas0jas** [comment]
Thanks, @maggie-j-liu!

**Pull request merged**
